.\" Manpage for Arbogen.
.\" Contact marwan.t.ghanem@gmail.com to correct errors or typos.
.TH man 1 "05 June 2013" "1.0" "Arbogen man page"
.SH NAME
Arbogen \- creates a random tree.
.SH SYNOPSIS
Arbogen [options][filename]
.SH DESCRIPTION
Arbogen is a ocaml based program that generates random trees depending on grammer passed in .spec files.

.SH OPTIONS
The following command-line options are recognized by Arbogen.

-version print version information

-interactive activate interactive mode

-verbose : set the verbosity level (a positive integer)

-min 	 : set the minimum size for the generated tree (a strictly positive integer)

-max	 : set the maximum size for the generated tree (a strictly positive integer)

-seed    : set the random generator seed

-eps1    : set the epsilon for singularity search (a strictly positive float number)

-eps1_factor: set the refinement factor for epsilon in singularity search (a strictly positive float number)

-eps2 : set the epsilon for Newton iteration (a strictly positive float number)

-eps2_factor : set the refinement factor for epsilon in Newton iteration (a strictly positive float number)

-try  : set the maximum of tries when generating trees

-type : set the type of output generated at the end

-file : set the name of the file to be created at end of execution

-zstart : sets the value of zstart

-help  :Display this list of options

--help : Display this list of options

.SH BUGS
No known bugs.
.SH AUTHOR
Frederic Peschanski (frederic.peschanski@lip6.fr)
